abvcbv/abvcbv/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view()),
    path('basic_app/', include('basic_app.urls', namespace = 'basic_app')),
]

abvcbv/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('', views.SchoolListView.as_view(), name = 'list'),
    path('<int:pk>/', views.SchoolDetailView.as_view(), name = 'detail'),
    path('create/', views.SchoolCreateView.as_view(), name = 'create'),
    path('update/<int:pk>/', views.SchoolUpdateView.as_view(), name = 'update'),
    path('delete/<int:pk>/', views.SchoolDeleteView.as_view(), name = 'delete'),
]

abvcbv/basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class School(models.Model):
    name = models.CharField(max_length = 256)
    principal = models.CharField(max_length = 256)
    location = models.CharField(max_length = 256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:detail", kwargs={'pk':self.pk})

class Student(models.Model):
    name = models.CharField(max_length = 256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete = models.CASCADE)

    def __str__(self):
        return self.name

abvcbv/basic_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (TemplateView,
                                  ListView,
                                  DetailView,
                                  CreateView,
                                  UpdateView,
                                  DeleteView, )
from . import models

class IndexView(TemplateView):
    template_name = 'index.html'


class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_detail.html'

class SchoolCreateView(CreateView):
    fields = ('name', 'principal', 'location')
    model = models.School
    template_name = 'basic_app/school_form.html'

class SchoolUpdateView(UpdateView):
    fields = ('name', 'principal')
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")

abvcbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
  <title>( ͡° ͜ʖ ͡°)</title>
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <ul class="nav navbar-nav">
      <li><a class="btn btn-dark btn-lg" role="button" href="{% url 'basic_app:list' %}">Скхолы</a></li>
      <li><a class="btn btn-dark btn-lg" role="button" href="{% url 'admin:index' %}">Адмэн</a></li>
      <li><a href="#"></a></li>
  </nav>

  <div class="container">
  {% block body_block %}
  {% endblock %}
  </div>
</body>
</html>

abvcbv/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}

<h1>Делетение {{ school.name }} ?</h1>

<form method="POST">
  {% csrf_token %}
  <input type="submit" class="btn btn-warning" value='Делетение'>
  <a href="{% url 'basic_app:detail' pk=school.pk%}">Кансер</a>
</form>

{% endblock %}

abvcbv/basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}

<div class="jumbotron">
  <h1>Паге оф скхола информатион</h1>
  <h2>Информатион:</h2>
  <p>Скхола ноим: {{ school_detail.name }}</p>
  <p>Дегенеректор: {{ school_detail.principal }}</p>
  <p>Лакатион: {{ school_detail.location }}</p>
  <h3>Ступидс:</h3>
  {% for student in school_detail.students.all %}
    <p>{{ student.name }}, ono imeet {{ student.age }} godov</p>
  {% endfor %}
</div>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <ul class="nav navbar-nav">
    <li><a class='btn btn-warning' href="{% url 'basic_app:update' pk=school_detail.pk %}">Упдате</a></li>
    <li><a class='btn btn-danger' href="{% url 'basic_app:delete' pk=school_detail.pk %}">Делетение</a></li>
    <li><a href="#"></a></li>
</nav>

{% endblock %}

abvcbv/basic_app/templates/basic_app/school_form.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}

<div class='jumbotron'>
<h1>
  {% if not form.instance.pk %}
  Сосание скхолы
  {% else %}
  Аптате скхола
  {% endif %}
</h1>

  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-success" value="Сенд">
  </form>
</div>

{% endblock %}

abvcbv/basic_app/templates/basic_app/school_list.html
{% extends 'basic_app/basic_app_base.html'%}

{% block body_block %}
<h1>Hallo there, schoolniki</h1>
<o1>
  {% for school in schools %}
  <h2><li><a href="{{school.id}}">{{ school.name }}</li></h2>
  {% endfor %}
</o1>
{% endblock %}

abvcbv/templates/base.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}

<div class="jumbotron">
  <h1>Паге оф скхола информатион</h1>
  <h2>Информатион:</h2>
  <p>Скхола ноим: {{ school_detail.name }}</p>
  <p>Дегенеректор: {{ school_detail.principal }}</p>
  <p>Лакатион: {{ school_detail.location }}</p>
  <h3>Ступидс:</h3>
  {% for student in school_detail.students.all %}
    <p>{{ student.name }}, ono imeet {{ student.age }} godov</p>
  {% endfor %}
</div>

<div class="container">
  <p><a class='btn btn-dark' href="{% url 'basic_app:update' pk=school_detail.pk %}">Упдате</a></p>
</div>

{% endblock %}

abvcbv/templates/index.html
{% extends "base.html" %}

{% block body_block%}
  <div class="jumbotron">
    <h1>Хоме паге</h1>
  </div>
{% endblock %}